export type PartnerCategory = "gov" | "company" | "school" | "individual";

export type PartnerContact = {
  name: string; // person's full name (EN preferred, AR fallback)
  nameAr?: string;
  position?: string; // job function / title
  emails: string[]; // 0..n, cleaned & de-duped
  phones: string[]; // 0..n, normalized UAE format, display strings
};

export type Partner = {
  id: string; // stable slug, e.g. "school-ain-al-khaleej"
  name: string; // organization name (EN)
  nameAr?: string;
  category: PartnerCategory;
  subtype?: string; // "Private" | "Public" | "Corporate" | ...
  mou: boolean; // true if from the "Schools with MOU" sheet
  status?: string; // "Confirmed" | "Updated" | free text from sheet
  logo?: string; // optional /brand/... path; usually absent → monogram
  website?: string; // optional
  contacts: PartnerContact[]; // one card may have multiple people
};

// Toggle to include the full (large) schools directory. Default OFF to keep
// the partners page curated. Regenerate after changing: node scripts/import-partners.mjs
export const SHOW_FULL_SCHOOLS = false;

// The array below is generated by scripts/import-partners.mjs from
// "Gala Dinner List (1).xlsx". Do not hand-edit between the markers.
// <auto>
export const PARTNERS_DATA: Partner[] = [
  {
    "id": "gov-abu-dhabi-agriculture-and-food-safety-authority",
    "name": "Abu Dhabi Agriculture and Food Safety Authority",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "حمد بن سالم العامري",
        "position": "مدير مكتب العين-هيئة أبوظبي لزراعة و السلامة",
        "emails": [
          "hamad.nassra@adafsa.gov.ae"
        ],
        "phones": [
          "055 612 2226"
        ]
      }
    ]
  },
  {
    "id": "gov-abu-dhabi-chamber",
    "name": "Abu Dhabi Chamber",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "شمة سالم الدرمكي",
        "position": "مسؤولة الفعاليات في غرفة ابوظبي - منطقة العين",
        "emails": [
          "shamma@adcci.gov.ae"
        ],
        "phones": [
          "03 707 6622"
        ]
      }
    ]
  },
  {
    "id": "gov-abu-dhabi-police",
    "name": "Abu Dhabi Police",
    "category": "gov",
    "mou": false,
    "status": "خارج البلاد",
    "contacts": [
      {
        "name": "Lieutenant Colone: Abdulaziz Al Qahtani",
        "emails": [
          "work.placement@adpolice.gov.ae"
        ],
        "phones": [
          "03 709 1522"
        ]
      },
      {
        "name": "Colonel Nasser Abdullah Al Saadi,",
        "position": "Head of security information in the Security Media Department of the police",
        "emails": [],
        "phones": []
      }
    ]
  },
  {
    "id": "gov-abu-dhabi-sewerage-services-company-al-ain-branch",
    "name": "Abu Dhabi Sewerage Services Company (Al Ain Branch)",
    "category": "gov",
    "mou": false,
    "status": "no answer",
    "contacts": [
      {
        "name": "Noura Obaid AlDhaheri",
        "emails": [
          "noura.obaid@adssc.ae"
        ],
        "phones": [
          "03 701 0631"
        ]
      }
    ]
  },
  {
    "id": "gov-abu-dhabi-tourism-culture-authority",
    "name": "Abu Dhabi Tourism & Culture Authority",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "الدكتور/ موسى الهواري",
        "position": "رئيس قسم تطوير المحتوى",
        "emails": [
          "musa.alhawari@tcaabudhabi.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "gov-abudhabi-quality-and-conformity-council",
    "name": "Abudhabi Quality and Conformity Council",
    "category": "gov",
    "mou": false,
    "status": "not coming",
    "contacts": [
      {
        "name": "Alyazia Alshamsi",
        "position": "Senior Analyst",
        "emails": [
          "alyazia.alshamsi@qcc.abudhabi.ae"
        ],
        "phones": [
          "050 336 4338"
        ]
      }
    ]
  },
  {
    "id": "gov-adek-aa",
    "name": "ADEK- AA",
    "category": "gov",
    "mou": false,
    "status": "Confirmed Attendance",
    "contacts": [
      {
        "name": "Mr. Ahmad Al Shamsi",
        "position": "مدير مكتب العين",
        "emails": [
          "Ahmed.alshamisi@adek.gov.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "gov-adqcc",
    "name": "ADQCC",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "Afnan Al Hamed",
        "position": "Administrive Assistant",
        "emails": [
          "afnan.alhamed@qcc.gov.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "gov-al-ain-department-of-economic-development",
    "name": "Al Ain Department of Economic Development",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "Khalid Hamar Ain Al Dhaheri",
        "position": "مدير سلطة ابوظبي للتسجيل- منطقة العين",
        "emails": [
          "Dedcpost@ded.abudhabi.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "gov-al-ain-municipality",
    "name": "Al Ain Municipality",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "Mohamed Al-Azani",
        "position": "HR Training Specialist",
        "emails": [
          "mohammed.alazzani@aam.gov.ae"
        ],
        "phones": [
          "050 618 6727"
        ]
      },
      {
        "name": "محمد جمعة نخيرة الظاهري",
        "position": "مستشار خدمات البلدية - بلدية العين",
        "emails": [],
        "phones": [
          "050 693 9292"
        ]
      },
      {
        "name": "Mr. Mubarak Al Shamesi",
        "position": "Knowledge and Innovation Management at Al Ain City Municipality",
        "emails": [],
        "phones": []
      }
    ]
  },
  {
    "id": "gov-al-ain-police",
    "name": "Al Ain Police",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "Hamad Al-Farisi",
        "position": "مدير فرع التدريب- مديرية شرطة العين",
        "emails": [
          "hf7372@gmail.com"
        ],
        "phones": [
          "050 533 7372"
        ]
      }
    ]
  },
  {
    "id": "gov-civil-defence",
    "name": "Civil Defence",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "سعادة العقيد/ مظفر محمد العامري",
        "position": "مدير إدارة الإنقاذ والأطفاء، هيئة أبوظبي للدفاع المدني، منطقة العين",
        "emails": [],
        "phones": [
          "050 999 3707"
        ]
      }
    ]
  },
  {
    "id": "gov-department-of-culture-tourism",
    "name": "Department of Culture & Tourism",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "Khalifa Al Shamesi (Emirates Hiratage)",
        "position": "مدير مركز العين- نادي تراث الإمارات",
        "emails": [
          "khalifa.butti4@gmail.com"
        ],
        "phones": [
          "050 618 7333"
        ]
      },
      {
        "name": "Hend Hamad Al Dhaheri",
        "emails": [
          "hend.aldhaheri@dctabudhabi.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "gov-department-of-economic-development",
    "name": "Department of Economic Development",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "Mohammed Alrumaithi",
        "position": "Senior HR officer",
        "emails": [
          "1087450@students.adu.ac.ae"
        ],
        "phones": [
          "050 414 1162"
        ]
      }
    ]
  },
  {
    "id": "gov-emirates-red-crescent",
    "name": "Emirates Red Crescent",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "Dr. Ahmad Obaid Aldhahri",
        "position": "General Director",
        "emails": [
          "a.aldhaheri@rcuae.ae"
        ],
        "phones": []
      },
      {
        "name": "Mr. Mohammad Saif Al Kindi",
        "emails": [
          "m.alkendi@rcuae.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "gov-ese",
    "name": "ESE",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "الأستاذ/ جمعة الشامسي",
        "position": "مسؤول تطوير جودة التعليم لمادة الرياضيات",
        "emails": [
          "juma.alshamisi@ese.gov.ae"
        ],
        "phones": []
      },
      {
        "name": "أستاذة / فلوة المري",
        "position": "مسؤول تطوير جودة التعليم لمواد العلوم",
        "emails": [
          "falwa.almerri@ese.gov.ae"
        ],
        "phones": []
      },
      {
        "name": "الأستاذة / أميرة البلوشي الفاضلة",
        "position": "مسؤول تطوير جودة التعليم لمواد العلوم",
        "emails": [
          "amira.albaloushi@ese.gov.ae"
        ],
        "phones": []
      },
      {
        "name": "الأستاذ عبدالعزيز الجنيبي",
        "position": "قسم الأنشطة",
        "emails": [
          "Abdulaziz.Junaibi@ese.gov.ae"
        ],
        "phones": []
      },
      {
        "name": "الاستاذ علي الجنيبي",
        "emails": [
          "Ali.Algunaibi@ese.gov.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "gov-family-care-authority",
    "name": "Family Care Authority",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "Maysoon Almeqbali",
        "position": "أخصائي ادماج وبرامج",
        "emails": [
          "maisoun.almeqbaali@adfca.gov.ae"
        ],
        "phones": [
          "050 730 1119"
        ]
      },
      {
        "name": "Khalid Mohammed Saeed Alsaedi",
        "emails": [
          "Khalid.Alsaedi@adfca.gov.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "gov-federal-identity-citizenship-emirates-id",
    "name": "Federal Identity & Citizenship - Emirates ID",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "Hammoud Mohammed Al Nuaimi",
        "position": "Center Manager",
        "emails": [
          "Hmoud.alnuaimi@icp.gov.ae"
        ],
        "phones": [
          "050 333 3145"
        ]
      }
    ]
  },
  {
    "id": "gov-food-control-authurity",
    "name": "Food Control Authurity",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "Kanna Al Maskari",
        "position": "Adminstration Manager",
        "emails": [
          "kanna.almaskari@adafsa.gov.ae"
        ],
        "phones": [
          "050 448 4499"
        ]
      }
    ]
  },
  {
    "id": "gov-ministry-of-defense",
    "name": "Ministry of Defense",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "Khadija",
        "position": "Supervisor",
        "emails": [
          "academy1@mod.gov.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "gov-shurooq",
    "name": "Shurooq",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "Humaid",
        "position": "Director, Procurement and Contract",
        "emails": [
          "H.alhosani@shurooq.gov.ae"
        ],
        "phones": [
          "050 869 2555"
        ]
      }
    ]
  },
  {
    "id": "gov-tamm",
    "name": "TAMM",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "Abdullah Al Harbi",
        "emails": [
          "tamm.centersdevelopment@adda.gov.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "gov-org-3",
    "name": "الدكتور عادل العبيدلي",
    "category": "gov",
    "mou": false,
    "status": "apologized",
    "contacts": [
      {
        "name": "الدكتور عادل العبيدلي",
        "position": "مدير مجلس 6 التعليمي",
        "emails": [
          "adel.alobaidly@ese.gov.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "gov-org",
    "name": "جهاز الامارات للمحاسبة",
    "category": "gov",
    "mou": false,
    "status": "اعتذرت مداوة بابوظبي",
    "contacts": [
      {
        "name": "هيفاء الشمري",
        "position": "مدير إدارة الموارد البشرية في جهاز الامارات للمحاسبة",
        "emails": [
          "info@uaeaa.gov.ae"
        ],
        "phones": [
          "050 214 4222"
        ]
      }
    ]
  },
  {
    "id": "gov-org-2",
    "name": "دائرة التمكين الحكومي",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "صالح سيف",
        "emails": [
          "saleh.saif@dge.gov.ae"
        ],
        "phones": [
          "055 333 3125"
        ]
      }
    ]
  },
  {
    "id": "gov-org-5",
    "name": "هيئة أبوظبي للدفاع المدني",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "النقيب/ جمعه البلوشي",
        "position": "مدير العلاقات العامه",
        "emails": [
          "j.albloushi@adcda.gov.ae"
        ],
        "phones": [
          "050 811 6110"
        ]
      }
    ]
  },
  {
    "id": "gov-org-4",
    "name": "هيئة أبوظبي للدفاع المدني ( أبوظبي)",
    "category": "gov",
    "mou": false,
    "contacts": [
      {
        "name": "المقدم/ حمدان حسن بن ذيبان",
        "position": "رئيس قسم الاتصال المؤسسي",
        "emails": [
          "hthayban@adcda.gov.ae"
        ],
        "phones": [
          "050 999 3930"
        ]
      }
    ]
  },
  {
    "id": "company-abu-dhabi-islamic-bank",
    "name": "Abu Dhabi Islamic Bank",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Ahmed Ratib",
        "position": "Bawadi Mall Manager",
        "emails": [
          "a.hassan@adib.com"
        ],
        "phones": [
          "050 760 0607"
        ]
      },
      {
        "name": "Ahmed Abdullah Albloushi",
        "position": "Area Manager",
        "emails": [
          "ahmedb@adib.com"
        ],
        "phones": [
          "050 618 6999"
        ]
      },
      {
        "name": "Mr. Ahmed Ateeq Al Dhahri",
        "position": "Head of Branches at UAE",
        "emails": [
          "aateeq@adib.com"
        ],
        "phones": [
          "050 713 3391",
          "050 513 3818"
        ]
      }
    ]
  },
  {
    "id": "company-abu-ghazaleh-group",
    "name": "Abu Ghazaleh Group",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Mr. Zaid Ghanumeh",
        "emails": [
          "Zghanayem@tagi.com"
        ],
        "phones": [
          "050 612 9513"
        ]
      }
    ]
  },
  {
    "id": "company-ad-media",
    "name": "AD Media",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Maha Alzaabi",
        "emails": [
          "Maha.AlZaabi@admedia.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-adeeb-group",
    "name": "Adeeb Group",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Dr. Ansari",
        "position": "Group CEO",
        "emails": [
          "ansari@adeebgroup.com"
        ],
        "phones": [
          "050 672 9706"
        ]
      }
    ]
  },
  {
    "id": "company-admn",
    "name": "ADMN",
    "category": "company",
    "mou": false,
    "status": "not coming",
    "contacts": [
      {
        "name": "Maha Al Hammadi",
        "position": "Specialist - Learning",
        "emails": [
          "Maha.AlHammadi@admn.ae"
        ],
        "phones": [
          "056 305 0224"
        ]
      }
    ]
  },
  {
    "id": "company-adnec",
    "name": "ADNEC",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Samar Wadie",
        "position": "Managers - Sales",
        "emails": [
          "samar.wadie@adnec.ae"
        ],
        "phones": [
          "050 831 4200"
        ]
      }
    ]
  },
  {
    "id": "company-adnoc",
    "name": "ADNOC",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Husain Saif",
        "position": "Office Administrator",
        "emails": [
          "husaif@adnoc.ae"
        ],
        "phones": [
          "050 555 5917",
          "050 330 5060"
        ]
      },
      {
        "name": "سلطان عيسى المهيري",
        "position": "senior Civil Engineer",
        "emails": [],
        "phones": [
          "054 477 4772"
        ]
      }
    ]
  },
  {
    "id": "company-aghtheyah-al-foaah",
    "name": "Aghtheyah Al Foa'ah",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Muna Hassan",
        "position": "Communication Manager",
        "emails": [
          "mona@agthia.com"
        ],
        "phones": [
          "050 231 3104"
        ]
      }
    ]
  },
  {
    "id": "company-agthia",
    "name": "Agthia",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Mouza Aldhaheri",
        "position": "HR Officer",
        "emails": [
          "maldhaheri@agthia.com"
        ],
        "phones": [
          "03 701 8701"
        ]
      }
    ]
  },
  {
    "id": "company-al-ain-club",
    "name": "Al Ain Club",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "عبيد الظاهري",
        "position": "مسؤول قسم الاتصال المؤسسي",
        "emails": [
          "oaldhaheri@alainfc.ae"
        ],
        "phones": [
          "050 662 2424"
        ]
      }
    ]
  },
  {
    "id": "company-al-ain-club-sports-and-cultural-company",
    "name": "Al Ain Club Sports and Cultural Company",
    "category": "company",
    "mou": false,
    "status": "not attending",
    "contacts": [
      {
        "name": "Amna Al Blooshi",
        "position": "مسؤول قسم المشتريات",
        "emails": [
          "aalblooshi@alainclub.ae"
        ],
        "phones": [
          "050 360 4074"
        ]
      }
    ]
  },
  {
    "id": "company-al-ain-farms",
    "name": "Al Ain Farms",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Aysha Hareb Al Dhaheri",
        "position": "Head Human Capital",
        "emails": [
          "aysha.aldhaheri@alainfarms.com"
        ],
        "phones": [
          "055 999 5609"
        ]
      },
      {
        "name": "Adnan Jamal",
        "position": "Manager L&D and PMS",
        "emails": [
          "Adnan.Jamal@alainfarms.com"
        ],
        "phones": [
          "050 173 4707"
        ]
      },
      {
        "name": "حسان صافي",
        "position": "الرئيس التنفيذي لمزارع العين",
        "emails": [
          "CEO_OFFICE@alainfarms.com"
        ],
        "phones": [
          "03 711 4590"
        ]
      }
    ]
  },
  {
    "id": "company-al-ain-golf-and-equestrian-club",
    "name": "Al Ain Golf and Equestrian Club",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Mr. Shane Peacock",
        "position": "Operating Manager",
        "emails": [
          "shane@aesgc.ae"
        ],
        "phones": [
          "054 329 7630"
        ]
      },
      {
        "name": "Hesham Adel",
        "position": "Assistant Banquet Manager",
        "emails": [
          "banquet@aesgc.ae"
        ],
        "phones": [
          "056 448 7452"
        ]
      }
    ]
  },
  {
    "id": "company-al-ain-pharmacy",
    "name": "Al Ain Pharmacy",
    "category": "company",
    "mou": false,
    "status": "ممكن 2 يحضروا",
    "contacts": [
      {
        "name": "Hanan Amer",
        "position": "Manager -TRAINING & GOVT AFFAIR",
        "emails": [
          "social@alain-pharmacy.com"
        ],
        "phones": [
          "050 124 6358"
        ]
      }
    ]
  },
  {
    "id": "company-al-awsaf-contracting",
    "name": "Al Awsaf contracting",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Eng. Haitham",
        "position": "project manager",
        "emails": [],
        "phones": [
          "055 111 7767"
        ]
      },
      {
        "name": "Eng. Younis Tabash",
        "position": "project manager",
        "emails": [],
        "phones": [
          "058 915 4644"
        ]
      },
      {
        "name": "Eng. Jibreel",
        "position": "General manager",
        "emails": [],
        "phones": [
          "055 446 1113"
        ]
      }
    ]
  },
  {
    "id": "company-al-dhaher",
    "name": "Al Dhaher",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "محمد الظاهر فارم",
        "emails": [],
        "phones": [
          "050 775 7617"
        ]
      }
    ]
  },
  {
    "id": "company-al-fahjan",
    "name": "Al Fahjan",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Eng.Sakt",
        "position": "Construction",
        "emails": [
          "alfahjan.ae@hotmail.com"
        ],
        "phones": [
          "03 721 7444",
          "052 907 6441"
        ]
      }
    ]
  },
  {
    "id": "company-al-fardan-exchange",
    "name": "Al Fardan Exchange",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Amr Sallam",
        "position": "Regional Manager",
        "emails": [
          "amr.adel@alfardanexchange.com"
        ],
        "phones": [
          "056 995 4700"
        ]
      },
      {
        "name": "Yusuf Saleh",
        "position": "Branch Manager",
        "emails": [
          "yusuf.saleh@alfardanexchange.com"
        ],
        "phones": [
          "052 375 7776"
        ]
      },
      {
        "name": "Hamda Al Shamsi",
        "position": "Team Leader",
        "emails": [
          "hamda.mubarak@alfardanexchange.com"
        ],
        "phones": [
          "050 135 8838"
        ]
      }
    ]
  },
  {
    "id": "company-al-futtaim-motors",
    "name": "Al Futtaim Motors",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Mohammad Sajid",
        "position": "Reception Manager",
        "emails": [
          "mohammad.sajid@alfuttaim.ae"
        ],
        "phones": [
          "055 101 7786"
        ]
      }
    ]
  },
  {
    "id": "company-alaan-tv",
    "name": "Alaan TV",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Sherouk Sabry",
        "position": "Receptionist / Admin assistant",
        "emails": [
          "sherouk.sabry@alaan.tv"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-alain-zoo",
    "name": "Alain zoo",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Mohamed Cheikh Kahwatih",
        "position": "Head Partnership And Revenue Development",
        "emails": [
          "mohd.cheikh@gmail.com"
        ],
        "phones": [
          "050 449 6990"
        ]
      },
      {
        "name": "khalfan Al Darmaki",
        "position": "Head of the internship department",
        "emails": [
          "internship@alainzoo.ae"
        ],
        "phones": []
      },
      {
        "name": "Yasmina/ Osama: 0504486533/ Juma AlKaabi",
        "position": "juma: HR Manager",
        "emails": [
          "Yasmeena.alhabshi@alainzoo.ae"
        ],
        "phones": [
          "050 628 1686",
          "03 799 2277"
        ]
      },
      {
        "name": "Ghanim Al Hajeri",
        "position": "Director general of alain zoo",
        "emails": [
          "ghanim.alhajeri@alainzoo.ae"
        ],
        "phones": [
          "052 788 8886"
        ]
      }
    ]
  },
  {
    "id": "company-alef-education",
    "name": "Alef Education",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Kawther Hourani , Eyad Darawsheh",
        "position": "Head of Training and Quality",
        "emails": [
          "kawther.hourani@alefeducation.com",
          "eyad.darawsheh@alefeducation.com"
        ],
        "phones": [
          "056 515 7546"
        ]
      }
    ]
  },
  {
    "id": "company-aloft-al-ain",
    "name": "Aloft Al Ain",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "وليد مصطفى",
        "emails": [
          "Waleed.Mustafa@marriott.com"
        ],
        "phones": [
          "03 713 8805",
          "056 545 8262"
        ]
      }
    ]
  },
  {
    "id": "company-alpha-data",
    "name": "Alpha Data",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "IT Infrastructure and Service",
        "position": "Vikas Pillai",
        "emails": [
          "vikas.pillai@alpha.ae"
        ],
        "phones": [
          "058 517 0369"
        ]
      }
    ]
  },
  {
    "id": "company-arab-canadian-medical-center",
    "name": "Arab Canadian Medical Center",
    "category": "company",
    "mou": false,
    "status": "الرقم غير صحيح",
    "contacts": [
      {
        "name": "Mohammad Hassuoneh",
        "position": "Director HR",
        "emails": [
          "hr@acmcae.com"
        ],
        "phones": [
          "03 722 9660"
        ]
      }
    ]
  },
  {
    "id": "company-arak-consultant",
    "name": "Arak Consultant",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Eng. Adel Al Shadid",
        "position": "general manager",
        "emails": [
          "adel@arakconsultanting.com"
        ],
        "phones": [
          "050 623 3012"
        ]
      },
      {
        "name": "Eng.Haitham Masoud",
        "emails": [
          "haitham@arakconsultanting.com"
        ],
        "phones": [
          "050 623 3012"
        ]
      }
    ]
  },
  {
    "id": "company-arak-consulting",
    "name": "Arak Consulting",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "المهندس عادل شديد",
        "position": "استشاري هندسي",
        "emails": [
          "adel@arakconsulting.com"
        ],
        "phones": [
          "050 623 1450"
        ]
      }
    ]
  },
  {
    "id": "company-arclight-services",
    "name": "Arclight Services",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Eng. Anwar",
        "emails": [
          "anwar.ali@arclightservices.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-arkan-group",
    "name": "Arkan Group",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Eng. Abdelaziz Asad",
        "position": "General Manager - Arkan",
        "emails": [
          "a.asad@arkan.ae"
        ],
        "phones": [
          "050 244 4122"
        ]
      },
      {
        "name": "Eng. Saeed Al Dhaheri",
        "position": "General Manager - ACF",
        "emails": [
          "s.aldhaheri@arkan.ae"
        ],
        "phones": [
          "050 665 8686"
        ]
      },
      {
        "name": "Saif Al Kaabi",
        "position": "HR & Admin Manager - ACF",
        "emails": [
          "s.alkaabi@arkan.ae"
        ],
        "phones": [
          "050 448 7447"
        ]
      },
      {
        "name": "Mr. Hugo Losad",
        "position": "CEO - Of Building Materials",
        "emails": [
          "Hugo.Losada@emiratessteel.com"
        ],
        "phones": []
      },
      {
        "name": "Mr. Haasan Al Dhanhani",
        "position": "People Department of Emirates Steel Arkan",
        "emails": [
          "Hassan.Aldhanhani@emiratessteel.com"
        ],
        "phones": []
      },
      {
        "name": "محمد العفاري",
        "position": "Deputy CEO of Building Materials",
        "emails": [
          "Mohammed.afari@emiratessteel.com"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-arkan-emirates-steel",
    "name": "Arkan-Emirates Steel",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Mr. Amr Shehata",
        "position": "Head of People Business Partner",
        "emails": [
          "amr.shehata@emiratessteel.com"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-ayla-hotel",
    "name": "Ayla Hotel",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "محمد سوسان",
        "position": "مدير عام - فندق آيلا",
        "emails": [
          "m.soussan@aylahotels.com"
        ],
        "phones": [
          "050 663 2376"
        ]
      },
      {
        "name": "Gaafar abdulmueaz",
        "position": "HR Manager",
        "emails": [
          "g.abdulmueaz@aylahotels.com"
        ],
        "phones": [
          "055 101 3137"
        ]
      }
    ]
  },
  {
    "id": "company-ayla-hotels-resorts",
    "name": "Ayla Hotels & Resorts",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Bayan Darwish",
        "position": "Event Sales Executive",
        "emails": [
          "b.darwish@aylahotels.com"
        ],
        "phones": [
          "055 902 9215"
        ]
      }
    ]
  },
  {
    "id": "company-basalt-engineering-cosulatancy",
    "name": "BASALT ENGINEERING COSULATANCY",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Eng. Mohammed Hasan Khani",
        "position": "Site Engineer",
        "emails": [
          "m.khani@basaltconsultant.com"
        ],
        "phones": [
          "03 748 2154",
          "052 923 2349"
        ]
      }
    ]
  },
  {
    "id": "company-beeah-in-al-ain",
    "name": "Bee’ah in Al-Ain",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Ms. Azzah Salah",
        "position": "Sustainability Manager",
        "emails": [
          "asalah@beeah.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-bhg",
    "name": "BHG",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Mohammed Alghussein",
        "position": "CEO",
        "emails": [
          "malghussein@binharmal.net"
        ],
        "phones": [
          "050 663 6777"
        ]
      }
    ]
  },
  {
    "id": "company-bin-ham-group",
    "name": "Bin Ham Group",
    "category": "company",
    "mou": false,
    "status": "attending",
    "contacts": [
      {
        "name": "Nabil Kamal Al Farra",
        "position": "Schools’ General Supervisor",
        "emails": [
          "n.kamal@binhamschools.com"
        ],
        "phones": [
          "037545171227"
        ]
      }
    ]
  },
  {
    "id": "company-bin-harmal-group",
    "name": "Bin Harmal Group",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "بلال غنام",
        "position": "مدير تنفيذي - مجموعة بن حرمل",
        "emails": [],
        "phones": [
          "050 338 9666"
        ]
      }
    ]
  },
  {
    "id": "company-binharmal-group",
    "name": "Binharmal Group",
    "category": "company",
    "mou": false,
    "status": "حضور بالانابة",
    "contacts": [
      {
        "name": "Hassan Rashid Al Bulushi",
        "position": "HR Director",
        "emails": [
          "hassan@binharmal.net"
        ],
        "phones": [
          "050 696 9220"
        ]
      }
    ]
  },
  {
    "id": "company-biomss",
    "name": "Biomss",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Sheila",
        "emails": [
          "Sheila@biomss.com"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-burjeel",
    "name": "Burjeel",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Yasal Arab",
        "position": "Operations manager",
        "emails": [
          "dryasal@gmail.com"
        ],
        "phones": [
          "054 791 5994"
        ]
      },
      {
        "name": "Dr. Aysha Almahri",
        "position": "Regional CEO",
        "emails": [
          "ceooffice.alain@burjeel.com"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-burjeel-hospital-vps-group",
    "name": "Burjeel Hospital - VPS Group",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Suhail Saheed",
        "position": "Regional Director - Al Ain",
        "emails": [
          "suhail.saheed@burjeel.com"
        ],
        "phones": [
          "056 402 1966"
        ]
      },
      {
        "name": "Mr. Maher Hamdan",
        "position": "Director of operations, Burjeel Royal Hospital Al Ain",
        "emails": [
          "maher.hamdan@burjeel.com"
        ],
        "phones": [
          "056 537 9413"
        ]
      }
    ]
  },
  {
    "id": "company-casio",
    "name": "CASIO",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Mohamad Kamar Eddine",
        "position": "Senior Educational Development Executive",
        "emails": [
          "eddinem@casio.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-cengage-learning",
    "name": "Cengage Learning",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Andrea Sidley MCMI",
        "emails": [
          "Andrea.Sidley@cengage.com"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-czech-rehabilitation-hospital",
    "name": "Czech Rehabilitation Hospital",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Dr. Mohammed Al Seiari",
        "position": "CEO",
        "emails": [
          "Crhceooffice@crh.ae"
        ],
        "phones": []
      },
      {
        "name": "Dr. Aly Ezzeldin",
        "position": "Rehabilitation Director",
        "emails": [],
        "phones": []
      },
      {
        "name": "Ms. Aisha Mustafa",
        "emails": [
          "Aishamustafa@crh.ae"
        ],
        "phones": [
          "056 229 6060"
        ]
      },
      {
        "name": "Dr. Rida Barouni,",
        "position": "Medical Manager",
        "emails": [
          "rida.b@crh.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-dewan-al-ain",
    "name": "Dewan - Al Ain",
    "category": "company",
    "mou": false,
    "status": "غير مؤكد",
    "contacts": [
      {
        "name": "Hessa Jauaan Abdulla Al Mheiri",
        "position": "HR Coordinator",
        "emails": [
          "hjmuhairi@alaindewan.ae"
        ],
        "phones": [
          "03 706 6361"
        ]
      }
    ]
  },
  {
    "id": "company-egypt-club-al-ain-city",
    "name": "Egypt club - Al Ain city",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Mohamed Fawzy",
        "position": "Public Relations And Maida Officer",
        "emails": [
          "egyclub.alain@gmail.com"
        ],
        "phones": [
          "055 802 8324"
        ]
      }
    ]
  },
  {
    "id": "company-elrace",
    "name": "Elrace",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Mr. Mohammed Abu Obeid , Sabah Maher",
        "position": "Executive Secretary",
        "emails": [
          "mohamed.ebeid@elrace.com",
          "sabah.maher@elrace.com"
        ],
        "phones": []
      },
      {
        "name": "NOOR EID HAMAYDEH",
        "position": "HR Officer",
        "emails": [
          "noor.hamaydeh@elrace.com"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-emirates-international-hospital",
    "name": "Emirates international hospital",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Patrick",
        "position": "Director of Emirates International Hospital",
        "emails": [
          "patrick@eih.ae"
        ],
        "phones": [
          "052 134 8490"
        ]
      }
    ]
  },
  {
    "id": "company-emirates-nbd",
    "name": "Emirates NBD",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Mohammed",
        "emails": [
          "MohammedKHALI@emiratesnbd.com"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-emmanuel-general-contracting-maintenance",
    "name": "Emmanuel General Contracting & Maintenance",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Eng . Manoj Sivan",
        "position": "General Manager",
        "emails": [],
        "phones": [
          "05560880470542661868"
        ]
      }
    ]
  },
  {
    "id": "company-exhubae",
    "name": "Exhubae",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Dr. Ahmad Al Attas",
        "emails": [
          "ahmadalattas.leadership@gmail.com"
        ],
        "phones": []
      },
      {
        "name": "Mr. Saeed Al Shamsi",
        "emails": [
          "SA@exhubae.com"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-finyal-media-llc",
    "name": "Finyal Media LLC",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Suhaib Aleses",
        "position": "Producer",
        "emails": [
          "suhaib@finyalmedia.com",
          "suhaibaleses@gmail.com"
        ],
        "phones": [
          "04 288 8266",
          "055 477 7127"
        ]
      }
    ]
  },
  {
    "id": "company-future-builders-contracting",
    "name": "Future Builders Contracting",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Eng. Attia Mostafa Mashaal",
        "position": "General Manager",
        "emails": [],
        "phones": [
          "052 551 7800"
        ]
      }
    ]
  },
  {
    "id": "company-hayat-biotech",
    "name": "Hayat Biotech",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "مروة حمودية",
        "position": "مدير مكتب المدير العام",
        "emails": [
          "maroua.hamoudia@hayatbiotech.com"
        ],
        "phones": [
          "056 401 5837"
        ]
      }
    ]
  },
  {
    "id": "company-huawei",
    "name": "Huawei",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Manufacturer",
        "position": "Osama",
        "emails": [
          "osama.osamaalhasan@h-partners.com"
        ],
        "phones": [
          "050 636 7101"
        ]
      }
    ]
  },
  {
    "id": "company-jacob",
    "name": "JACOB",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Sanjay Mandal",
        "emails": [
          "sanjay.mandal@jacobs.com"
        ],
        "phones": [
          "050 994 7624"
        ]
      }
    ]
  },
  {
    "id": "company-juton",
    "name": "Juton",
    "category": "company",
    "mou": false,
    "status": "غير مؤكد",
    "contacts": [
      {
        "name": "Osama Mansour",
        "position": "Al Ain Area manager",
        "emails": [
          "mansoo@jotun.com"
        ],
        "phones": [
          "050 745 1074"
        ]
      },
      {
        "name": "Iman Alali",
        "position": "Senoir HR Advisor",
        "emails": [
          "Iman.Alali@jotunadh.ae"
        ],
        "phones": [
          "050 444 3863"
        ]
      }
    ]
  },
  {
    "id": "company-juton-dubai",
    "name": "Juton( dubai)",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Safaa Hakim",
        "position": "HR Manager",
        "emails": [
          "Safaa.Hakim@jotunadh.ae"
        ],
        "phones": [
          "056 655 6197"
        ]
      }
    ]
  },
  {
    "id": "company-kanad-hospital",
    "name": "Kanad Hospital",
    "category": "company",
    "mou": false,
    "status": "Out of Country",
    "contacts": [
      {
        "name": "Ms. Mariel Castillo",
        "position": "Administrative Assistant",
        "emails": [
          "Maridel.castillo@kanadhospital.org"
        ],
        "phones": [
          "03 713 1140"
        ]
      },
      {
        "name": "New CEO",
        "emails": [],
        "phones": [
          "054 333 0828"
        ]
      }
    ]
  },
  {
    "id": "company-khatib-alami",
    "name": "Khatib & Alami",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Satyakama Agastya Martadiradja",
        "position": "Senior Design Architect",
        "emails": [
          "Satyakama.martadiradja@khatibalami.com"
        ],
        "phones": [
          "06 597 1670"
        ]
      }
    ]
  },
  {
    "id": "company-lavajet-al-ain",
    "name": "LAVAJET AL AIN",
    "category": "company",
    "mou": false,
    "status": "بده نص ساعه",
    "contacts": [
      {
        "name": "ahmed Abu Ibaid",
        "position": "HR MANAGER",
        "emails": [
          "a.qudaih@lavajet.ae"
        ],
        "phones": [
          "050 641 4470"
        ]
      },
      {
        "name": "fadi abu shanab",
        "position": "HR Senior Controller",
        "emails": [
          "f.hassan@lavajet.ae"
        ],
        "phones": [
          "056 998 0494"
        ]
      },
      {
        "name": "MOHAMMAD ELSERIEF",
        "position": "HR Officer",
        "emails": [
          "m.taha@lavajet.ae"
        ],
        "phones": [
          "050 635 5216"
        ]
      }
    ]
  },
  {
    "id": "company-lazourdy-contracting-gen-maintenance",
    "name": "Lazourdy Contracting & Gen. Maintenance",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Eng. Abdallah Kseibi",
        "position": "Project Manager",
        "emails": [],
        "phones": [
          "056 555 9899"
        ]
      }
    ]
  },
  {
    "id": "company-lg-district-cooling-international-llc",
    "name": "LG / District Cooling International LLC",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Mr. Yazan Al Omari",
        "position": "General Manager",
        "emails": [],
        "phones": [
          "052 132 4765",
          "054 521 9292"
        ]
      }
    ]
  },
  {
    "id": "company-liwa-college-director",
    "name": "Liwa College-Director",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Ahmed Abdelraouf Osman",
        "emails": [
          "Ahmed.Abdelraouf@ic.ac.ae"
        ],
        "phones": [
          "050 477 9248"
        ]
      }
    ]
  },
  {
    "id": "company-lulu-group",
    "name": "Lulu Group",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Nanda Kumar",
        "position": "Director of Marketing & Corporate Communications",
        "emails": [
          "nandakumar@ae.lulumea.com"
        ],
        "phones": [
          "050 445 6869"
        ]
      }
    ]
  },
  {
    "id": "company-mcsaatchi",
    "name": "M&CSAATCHI",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Shanty Jackson",
        "position": "Office Manager",
        "emails": [
          "shanty.jackson@mcsaatchi.com"
        ],
        "phones": [
          "050 961 4783"
        ]
      }
    ]
  },
  {
    "id": "company-marmum",
    "name": "Marmum",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Mahesh Sharma",
        "position": "HR & Admin Manager",
        "emails": [
          "mahesh.sarma@marmum.ae"
        ],
        "phones": [
          "050 373 3104"
        ]
      },
      {
        "name": "Ahmad Awad",
        "position": "Planning Manager",
        "emails": [
          "ahmad.awad@marmum.ae"
        ],
        "phones": [
          "054 997 0314"
        ]
      }
    ]
  },
  {
    "id": "company-masdar",
    "name": "Masdar",
    "category": "company",
    "mou": false,
    "status": "مغلق",
    "contacts": [
      {
        "name": "علي الشمري (خريج الجامعة)",
        "position": "رئيس ادارة المشاريع الاستراتيجية والخاصة",
        "emails": [
          "aalshimmari@masdar.ae"
        ],
        "phones": [
          "050 154 1543"
        ]
      }
    ]
  },
  {
    "id": "company-mauzan",
    "name": "Mauzan",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Ahmad Kasid",
        "position": "HR Assistant",
        "emails": [
          "ahmad.kasid@mauzan.com"
        ],
        "phones": [
          "037810424122"
        ]
      }
    ]
  },
  {
    "id": "company-mcgraw-hill-education",
    "name": "McGraw-Hill Education",
    "category": "company",
    "mou": false,
    "status": "apologized",
    "contacts": [
      {
        "name": "Sean Glynn and Maria",
        "emails": [
          "Sean.Glynn@mheducation.com",
          "maria.ibrahim@mheducation.com"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-mediclinic",
    "name": "MEDICLINIC",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Hassan",
        "emails": [
          "Hassan.Nammah@mediclinic.ae"
        ],
        "phones": []
      },
      {
        "name": "Mr. Philip Tyler",
        "position": "Hospital Director",
        "emails": [
          "philip.tyler@mediclinic.ae"
        ],
        "phones": [
          "056 414 9249"
        ]
      },
      {
        "name": "Dr. Tariq Shadid",
        "position": "Medical Director",
        "emails": [
          "Tariq.Shadid@mediclinic.ae"
        ],
        "phones": [
          "050 833 1276"
        ]
      }
    ]
  },
  {
    "id": "company-medicom-scientific-equipment-trading-llc",
    "name": "Medicom Scientific Equipment Trading LLC",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Nezar Alali",
        "position": "General Manager",
        "emails": [
          "nezar@medicom-grp.com"
        ],
        "phones": [
          "050 550 7242"
        ]
      }
    ]
  },
  {
    "id": "company-mindfire-it",
    "name": "Mindfire IT",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Cyber Security",
        "position": "Rejeesh",
        "emails": [
          "rejeesh@mindfireit.com"
        ],
        "phones": [
          "054 704 3130"
        ]
      }
    ]
  },
  {
    "id": "company-nael-and-bin-harmal-investment-company",
    "name": "Nael and bin harmal investment company",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Khalaf",
        "position": "Operation manager",
        "emails": [
          "drkhalaf@nbhi.net"
        ],
        "phones": [
          "055 590 4118"
        ]
      }
    ]
  },
  {
    "id": "company-nayel-and-bin-harmel-group",
    "name": "Nayel and bin harmel group",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "عبد الرحيم درويش",
        "position": "مجموعة نايل و بن حرمل",
        "emails": [],
        "phones": [
          "055 589 1400"
        ]
      }
    ]
  },
  {
    "id": "company-newcentury-education",
    "name": "Newcentury Education",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "دينا خفش",
        "emails": [
          "dina.khuffash@nceducation.com"
        ],
        "phones": [
          "056 459 1212"
        ]
      },
      {
        "name": "نادر فهمي",
        "emails": [
          "nader.deis@nceducation.com"
        ],
        "phones": [
          "056 996 9782"
        ]
      }
    ]
  },
  {
    "id": "company-next-consultant",
    "name": "Next Consultant",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Eng. Salah Ateeq",
        "position": "Al Ain Branch Manager",
        "emails": [],
        "phones": [
          "050 330 5104"
        ]
      },
      {
        "name": "Eng. Hosni Mohamed",
        "position": "project manager",
        "emails": [],
        "phones": [
          "055 584 0670"
        ]
      }
    ]
  },
  {
    "id": "company-next-engineering-consultants-al-ain-branch",
    "name": "Next Engineering Consultants – Al Ain Branch",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Dalia Moustafa ,, المهندس صلاح",
        "position": "Secretary",
        "emails": [
          "nextain0@eim.ae",
          "alain@next-engineering.com"
        ],
        "phones": [
          "03 766 7820",
          "050 259 7585"
        ]
      }
    ]
  },
  {
    "id": "company-nikon",
    "name": "Nikon",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Ms. Arya Chitra",
        "position": "General Manager",
        "emails": [
          "arya@nikonyouthschool.com"
        ],
        "phones": [
          "055 825 2728"
        ]
      }
    ]
  },
  {
    "id": "company-nmc",
    "name": "NMC",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Muralidharan Veerabhadran",
        "position": "General Manager",
        "emails": [
          "muralidharan.v@nmc.ae"
        ],
        "phones": []
      },
      {
        "name": "Rinshad Mohammed Ibrahim",
        "position": "Operations Manager",
        "emails": [
          "rinshad.ibrahim@nmc.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-overlord-systems",
    "name": "Overlord Systems",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Omar Mahdi",
        "position": "Founder & CEO",
        "emails": [
          "omar@overlordsystems.com"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-oxford-technologies",
    "name": "Oxford Technologies",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "IT Infrastructure and Service",
        "position": "Jilesh",
        "emails": [
          "jilesh@oxin.ae"
        ],
        "phones": [
          "052 951 5100"
        ]
      }
    ]
  },
  {
    "id": "company-pioneer-engineering",
    "name": "Pioneer Engineering",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Eng. Sami Sayed",
        "position": "general manager",
        "emails": [],
        "phones": [
          "050 318 2521"
        ]
      }
    ]
  },
  {
    "id": "company-prime-engineering",
    "name": "Prime Engineering",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Yaser Al-Omari",
        "emails": [
          "yaser@prime-engineering-projects.com"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-royal-dome-engineering-consultancyal-ain",
    "name": "ROYAL DOME ENGINEERING CONSULTANCYAl Ain",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Muhannad abdul jalil",
        "position": "Engineer",
        "emails": [
          "royal.dome@yahoo.com"
        ],
        "phones": [
          "03 737 0855",
          "055 783 5634"
        ]
      }
    ]
  },
  {
    "id": "company-save-fast",
    "name": "Save Fast",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Osama AbuWishah",
        "position": "Vice Chairman",
        "emails": [
          "osama@sfast.ae"
        ],
        "phones": [
          "050 292 9711"
        ]
      }
    ]
  },
  {
    "id": "company-shaun-technologies",
    "name": "Shaun Technologies",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Mr Irfan Muneer",
        "position": "Marketing Manager",
        "emails": [
          "irfan.muneer@shauntechnologies.ae"
        ],
        "phones": [
          "052 969 7775"
        ]
      }
    ]
  },
  {
    "id": "company-sheikh-tahnoon-bin-mohammed-medical-city",
    "name": "Sheikh Tahnoon Bin Mohammed Medical City",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Shamma Mohammed Al Ktebi",
        "position": "Training and Career Development Officer",
        "emails": [
          "sketbi@seha.ae"
        ],
        "phones": [
          "03 717 7029"
        ]
      },
      {
        "name": "Sara Kahthani- HR officer",
        "emails": [
          "sqahtani@seha.ae"
        ],
        "phones": []
      },
      {
        "name": "Mariam Al Humairi/ Sara Kahthani- HR officer",
        "emails": [
          "MHAMIRI@seha.ae"
        ],
        "phones": [
          "050 833 1146",
          "050 449 5565",
          "050 335 8787"
        ]
      },
      {
        "name": "Mohammed AlKwaiti",
        "position": "people care manager - مدير رعاية الافراد",
        "emails": [
          "moalkuwaiti@seha.ae"
        ],
        "phones": [
          "050 449 5565"
        ]
      }
    ]
  },
  {
    "id": "company-smbkc",
    "name": "SMBKC مؤسسات الشيخ محمد بن خالد آل نهيان الثقافي",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Mariam Al Shamsi",
        "position": "الأمين العام",
        "emails": [
          "Collaborations@smbkc-cultural.com",
          "Khoulodasd@gmail.com"
        ],
        "phones": [
          "050 122 0550"
        ]
      }
    ]
  },
  {
    "id": "company-stanford-engineering-consultant-and-interior-design",
    "name": "Stanford engineering consultant and interior design",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Khaled elsaid",
        "position": "Architectural designer engineer",
        "emails": [
          "stanford.eng@hotmail.com"
        ],
        "phones": [
          "03 751 8325",
          "050 501 1509"
        ]
      }
    ]
  },
  {
    "id": "company-strata",
    "name": "Strata",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Mr. Ismail Ali Abdulla , (His assistantMs. Huda Alkatheeri)",
        "position": "Managing Director",
        "emails": [
          "iaabdulla@strata.ae",
          "halkatheeri@strata.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-strata-manufacturing-pjsc",
    "name": "STRATA Manufacturing PJSC",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Ms. Amal Alkaabi",
        "position": "Learning and Development Coordinator",
        "emails": [
          "AAAlkaabi@strata.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-tadweer",
    "name": "Tadweer",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Ms. Nashwa Al Amri",
        "position": "Public Awareness Coordinator",
        "emails": [
          "nashwa.alameri@tadweer.ae"
        ],
        "phones": []
      },
      {
        "name": "Mr. Ali Al Dhaheri",
        "position": "CEO and Managing Director",
        "emails": [],
        "phones": []
      }
    ]
  },
  {
    "id": "company-taqa",
    "name": "TAQA",
    "category": "company",
    "mou": false,
    "status": "غير مؤكد",
    "contacts": [
      {
        "name": "Faleh Alshamsi",
        "position": "Electricty Operation & Maintenance Director",
        "emails": [
          "faleha@aadc.ae",
          "FalehA@taqadistribution.com"
        ],
        "phones": [
          "050 449 0330"
        ]
      },
      {
        "name": "Qais Al Suweidi",
        "position": "Vice President of Sustainability",
        "emails": [],
        "phones": []
      }
    ]
  },
  {
    "id": "company-taqa-transmission",
    "name": "TAQA transmission",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Hessa Wajdi Ali Aqab",
        "position": "Training & Career Development Assistant",
        "emails": [
          "hessa.aqab@taqatransmission.com"
        ],
        "phones": [
          "02 416 4662",
          "056 430 5550"
        ]
      },
      {
        "name": "aysha aldhahri",
        "position": "senoir Training & Career Development",
        "emails": [],
        "phones": []
      }
    ]
  },
  {
    "id": "company-tawam-hospital",
    "name": "Tawam Hospital",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Noura Salmeen Al-Kathiri",
        "emails": [
          "nkathiri@seha.ae"
        ],
        "phones": [
          "03 767 7444"
        ]
      }
    ]
  },
  {
    "id": "company-technical-specifications-for-gen-cont-est",
    "name": "Technical Specifications FOR GEN. CONT. EST",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Eng. Moemen Arabasi.",
        "position": "Site Civil Engineer",
        "emails": [
          "moemen.arabasi456@gmail.com"
        ],
        "phones": [
          "03 755 4330",
          "052 989 6727"
        ]
      }
    ]
  },
  {
    "id": "company-technology-innovate-institute",
    "name": "Technology Innovate Institute",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Mr. Adil Madkouri",
        "position": "Director – Special Projects",
        "emails": [
          "Adil.Madkouri@tii.ae",
          "Adil.madkouri@aspireuae.ae"
        ],
        "phones": [
          "056 219 8944"
        ]
      }
    ]
  },
  {
    "id": "company-the-bag-broker",
    "name": "The Bag Broker",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Mr Zafar Sindhu",
        "position": "Regional Sales Manager, Middle East",
        "emails": [
          "zafar.sindhu@thebagbroker.com"
        ],
        "phones": [
          "058 567 3359"
        ]
      }
    ]
  },
  {
    "id": "company-the-green-spoon",
    "name": "The Green Spoon",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Hanan Chaaibi",
        "position": "Co-Founder and Director",
        "emails": [
          "hanan@thegreenspoon.org"
        ],
        "phones": [
          "050 624 6408"
        ]
      },
      {
        "name": "Dilara Ozmeric",
        "position": "Co-Founder and Head of Research",
        "emails": [
          "dilara@thegreenspoon.org"
        ],
        "phones": [
          "058 507 1001"
        ]
      }
    ]
  },
  {
    "id": "company-zayed-house-for-islamic-culture",
    "name": "Zayed House for Islamic Culture",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Omer Al-Badi",
        "emails": [
          "o.albadi@zhic.ae"
        ],
        "phones": [
          "055 844 5886",
          "050 233 6553"
        ]
      }
    ]
  },
  {
    "id": "company-zayed-library",
    "name": "Zayed Library",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Aysha Nasser Al Hamiri; Mr. Hussein",
        "position": "HJunaibi@dctabudhabi.ae",
        "emails": [
          "aysha.alhamiri@dctabudhabi.ae"
        ],
        "phones": [
          "052 959 2999"
        ]
      }
    ]
  },
  {
    "id": "company-zoud-institution",
    "name": "zoud institution",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "Salem Alshamsi",
        "position": "Procurement Manager",
        "emails": [
          "salem.alshamsi@zoud.ae"
        ],
        "phones": [
          "050 336 6193"
        ]
      }
    ]
  },
  {
    "id": "company-org-2",
    "name": "بنك الامارات دبي الوطني",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "آمنة",
        "position": "HR Manager",
        "emails": [
          "Amnaabdul@emiratesnbd.com"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "company-org",
    "name": "بوادي مول",
    "category": "company",
    "mou": false,
    "contacts": [
      {
        "name": "خالد شريم",
        "position": "مدير عام التأجير و تطوير الأعمال / مجموعة نايل و بن حرمل",
        "emails": [
          "khalid@nbhi.net"
        ],
        "phones": [
          "050 663 7375"
        ]
      }
    ]
  },
  {
    "id": "school-org-24",
    "name": "أكاديمية المستقبل",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Ms Suheir",
        "nameAr": "السيدة سهير",
        "position": "Principal",
        "emails": [
          "fia.info@fischools.com",
          "Principal@fischools.com"
        ],
        "phones": [
          "03 764 6888",
          "050 455 6220"
        ]
      }
    ]
  },
  {
    "id": "school-org-19",
    "name": "التفوق العلمي الخاصة",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Mr. Ahmed Abdelfattah Hamed",
        "nameAr": "أحمد عبدالفتاح حامد ابراهيم",
        "position": "School Principal",
        "emails": [
          "scidistinction.pvt@moe.gov.ae",
          "aa02170218@gmail.com"
        ],
        "phones": [
          "03 761 4455",
          "055 656 8300"
        ]
      }
    ]
  },
  {
    "id": "school-org-13",
    "name": "المدرسة الأمريكية في العين",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Ms. Ruba Shadid",
        "nameAr": "ربى شديد",
        "position": "Principal",
        "emails": [
          "ruba.shadid@alainamericanschool.ae"
        ],
        "phones": [
          "050 441 5335"
        ]
      }
    ]
  },
  {
    "id": "school-org-20",
    "name": "المدرسة المتحدة في اليحر",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Mr. Raed",
        "nameAr": "الاستاذ رائد",
        "position": "Principal",
        "emails": [
          "9216@adek.gov.ae",
          "raed@unitedschool.com"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "school-org-22",
    "name": "المدرسة الوطنية الامريكية",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Dr. Denis M Peter",
        "nameAr": "دكتور دينيس",
        "position": "Principal",
        "emails": [
          "denis.peters@anschool.ae"
        ],
        "phones": [
          "052 421 8065"
        ]
      }
    ]
  },
  {
    "id": "school-org-10",
    "name": "دار العلوم الخاصة-العين",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Mr. REYAD IBRAHIM MAHMOOD KHALED",
        "nameAr": "رياض ابراهيم محمود خالد",
        "position": "School Principal",
        "emails": [
          "daraluloomaa.pvt@moe.gov.ae",
          "9186@adek.gov.ea",
          "reyadkh@gmail.com"
        ],
        "phones": [
          "03 767 6514",
          "050 643 0463",
          "056 323 3001"
        ]
      }
    ]
  },
  {
    "id": "school-org-12",
    "name": "زاخر الخاصة",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Mr. Abdul Azez Akhdir Suliman",
        "nameAr": "عبدالعزيز اخضير السليمان",
        "position": "School Principal",
        "emails": [
          "zakher.pvt@moe.gov.ae",
          "motab.soliman1980@gmail.com"
        ],
        "phones": [
          "03 781 1810",
          "055 604 6113"
        ]
      }
    ]
  },
  {
    "id": "school-org-11",
    "name": "لبنان الأولى الخاصة",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Nasir Yousef Al",
        "nameAr": "ناصر يوسف",
        "position": "School Principal",
        "emails": [
          "firstlebanon.pvt@moe.gov.ae",
          "naseermahameed@gmail.com"
        ],
        "phones": [
          "03 780 6780",
          "056 613 6367"
        ]
      }
    ]
  },
  {
    "id": "school-org-17",
    "name": "مدارس الخليل الدولية الخاصة",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Mr. GHAZWAN ABDUL WAHAB KAIAL",
        "nameAr": "غزوان كيال",
        "position": "Principal",
        "emails": [
          "alkhalilint.pvt@moe.gov.ae",
          "ghazwankaiali@gmail.com",
          "ghazwan.kaial@alkhalilschools.com"
        ],
        "phones": [
          "03 782 0676",
          "050 448 0648"
        ]
      }
    ]
  },
  {
    "id": "school-org-8",
    "name": "مدارس الظفرة الخاصة - العين",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Dr. Salam Omar",
        "nameAr": "نائبة الرئيس لينا / الدكتورة سلام عمر",
        "position": "Principal",
        "emails": [
          "info.al@dhafraschools.com",
          "salam.omar@dhafraschools.com"
        ],
        "phones": [
          "03 701 3999",
          "03 701 3998"
        ]
      }
    ]
  },
  {
    "id": "school-org-2",
    "name": "مدرسة الأضواء الخاصة",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Ms. Amira Gafer",
        "nameAr": "أميرة جعفر قريش",
        "position": "Principal",
        "emails": [
          "adwa@aladhwa-sch.net",
          "amira@aladhwa-sch.net"
        ],
        "phones": [
          "03 782 8870",
          "050 743 1209"
        ]
      }
    ]
  },
  {
    "id": "school-org-16",
    "name": "مدرسة الأندلس الخاصة",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Dr. Yahia AlDmour",
        "nameAr": "الدكتور يحيى عبد الفتاح الضمور",
        "position": "Principal",
        "emails": [
          "alandalus.ae@gmail.com",
          "Yahya.aldmour72@gmail.com"
        ],
        "phones": [
          "03 782 9980",
          "050 101 9039"
        ]
      }
    ]
  },
  {
    "id": "school-org-26",
    "name": "مدرسة الاتحاد الوطنية الخاصة - العين",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Shaikha Al Shamsi",
        "nameAr": "شيخة الشامسي",
        "position": "Principal",
        "emails": [
          "communication@inpsaa.com",
          "Shaikha.alshamsi@inpsaa.com",
          "Aaslihajar2202@gmail.com"
        ],
        "phones": [
          "03 781 1164",
          "050 643 4234"
        ]
      }
    ]
  },
  {
    "id": "school-org-23",
    "name": "مدرسة الامارات الخاصة",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Ms. Jameela Mohammed Alkatbi",
        "nameAr": "جميلة محمد الكتبي",
        "position": "Principal",
        "emails": [
          "9155@adek.gov.ae",
          "J.alketbi819@gmail.com"
        ],
        "phones": [
          "03 767 9322",
          "050 819 8800"
        ]
      }
    ]
  },
  {
    "id": "school-org-25",
    "name": "مدرسة الامارات الوطنية",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "دكتور محمد العدوان",
        "position": "Principal",
        "emails": [
          "9154@adek.gov.ae",
          "m.aladwan@aac.ens.sch.ae"
        ],
        "phones": [
          "03 707 0548",
          "055 171 6325"
        ]
      },
      {
        "name": "Dr. Akram Haik",
        "nameAr": "دكتور اكرم",
        "position": "Principal boys section",
        "emails": [
          "a.haik@aac.ens.sch.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "school-org-9",
    "name": "مدرسة الحمدانية الكبرى",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Dr. Wadie Wasef",
        "nameAr": "الدكتور وديع واصف مصطفى",
        "position": "Principal",
        "emails": [
          "9140@adek.gov.ae",
          "Wadie.wasef@gmail.com"
        ],
        "phones": [
          "03 781 3114",
          "050 630 5900"
        ]
      }
    ]
  },
  {
    "id": "school-org-4",
    "name": "مدرسة الصنوبر الخاصة",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Mrs. Rima Sarieddine",
        "nameAr": "السيدة ريما سريدين",
        "position": "Principal",
        "emails": [
          "sanawbar@emirates.net.ae",
          "rima.sarieddine@alsanawbarschool.com"
        ],
        "phones": [
          "03 767 9889",
          "050 618 5043"
        ]
      }
    ]
  },
  {
    "id": "school-org-3",
    "name": "مدرسة العين جونيورز الخاصة",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Mohammad Gaffar",
        "nameAr": "محمد جعفر",
        "position": "Principal",
        "emails": [
          "info@alainjuniors.com",
          "mohd.gaffar@alainjuniors.com"
        ],
        "phones": [
          "03 781 0077",
          "050 839 1174"
        ]
      }
    ]
  },
  {
    "id": "school-org-7",
    "name": "مدرسة المستقبل",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Dr. Tonia Williams",
        "nameAr": "الدكتورة تونيـا ويليامز",
        "position": "Principal",
        "emails": [
          "info@fischools.ae",
          "tonia.williams@fischools.ae"
        ],
        "phones": [
          "03 766 6771",
          "058 973 4633",
          "050 593 9171"
        ]
      }
    ]
  },
  {
    "id": "school-org-5",
    "name": "مدرسة براعم العين الخاصة",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Dr. Hussein",
        "nameAr": "الدكتور حسين ابو رتيمة",
        "position": "Principal",
        "emails": [
          "baraem.alain77@yahoo.com",
          "hussein20000@hotmail.com"
        ],
        "phones": [
          "03 767 8848",
          "050 793 1272"
        ]
      }
    ]
  },
  {
    "id": "school-org-6",
    "name": "مدرسة جزيرة أبوظبي",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Dr. Hisham Hejazin",
        "nameAr": "الدكتور هشام حجازين",
        "position": "Principal",
        "emails": [
          "info@adiips.ae",
          "hishamhj2002@yahoo.com"
        ],
        "phones": [
          "03 722 7666",
          "052 678 6520"
        ]
      }
    ]
  },
  {
    "id": "school-org-18",
    "name": "مدرسة صقر الامارات الخاصة",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Ms. Antoinet Nasrallah",
        "nameAr": "أنطوانيت نصرالله",
        "position": "Principal",
        "emails": [
          "9153@adek.gov.ae",
          "antwa65@hotmail.com"
        ],
        "phones": [
          "03 780 6668",
          "050 619 4099"
        ]
      }
    ]
  },
  {
    "id": "school-org",
    "name": "مدرسة عين الخليج الخاصة",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Raed Kasrawi",
        "nameAr": "رائد القصراوي",
        "position": "Principal",
        "emails": [
          "raed.husein@ainalkhaleejprivateschools.com"
        ],
        "phones": [
          "03 781 1232",
          "050 231 2384"
        ]
      }
    ]
  },
  {
    "id": "school-org-14",
    "name": "مدرسة ليوا الدولية",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "status": "hala.makki@liwaschool.com",
    "contacts": [
      {
        "name": "John Harris",
        "position": "Principal",
        "emails": [
          "info@liwaschool.com",
          "activities@liwaschool.com",
          "john.harris@liwaschool.com"
        ],
        "phones": [
          "03 781 0444",
          "050 236 6708"
        ]
      }
    ]
  },
  {
    "id": "school-org-15",
    "name": "مدرسة ليوا للبنات",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Ms. Hanna",
        "position": "vice Pricipal",
        "emails": [
          "info@lisg.ae"
        ],
        "phones": [
          "03 780 0444",
          "050 236 6987"
        ]
      }
    ]
  },
  {
    "id": "school-org-21",
    "name": "مدرسة مدار الدولية",
    "category": "school",
    "subtype": "Private",
    "mou": true,
    "contacts": [
      {
        "name": "Ms. Alaa Jbouri",
        "nameAr": "الاء جبوري",
        "position": "Principal",
        "emails": [
          "communication@madarschool.ae",
          "principal@madarschool.ae"
        ],
        "phones": [
          "03 761 1330",
          "054 445 5114"
        ]
      }
    ]
  },
  {
    "id": "ind-abu-dhabi-agriculture-and-food-safety-authority",
    "name": "Abu Dhabi Agriculture and Food Safety Authority",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "حمد بن سالم العامري",
        "position": "مدير مكتب العين-هيئة أبوظبي لزراعة و السلامة",
        "emails": [
          "hamad.nassra@adafsa.gov.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-abu-dhabi-chamber-of-commerce-industry",
    "name": "Abu Dhabi Chamber of Commerce & Industry",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "شمة سالم الدرمكي",
        "position": "مسؤولة الفعاليات في غرفة ابوظبي - منطقة العين",
        "emails": [
          "shamma@adcci.gov.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-abu-dhabi-islamic-bank",
    "name": "Abu Dhabi Islamic Bank",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "Mr. Ahmed Ateeq Al Dhahri",
        "position": "Head of Branches at UAE",
        "emails": [
          "aateeq@adib.com"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-abu-dhabi-police",
    "name": "Abu Dhabi Police",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "Colonel Nasser Abdullah Al Saadi,",
        "position": "Head of security information in the Security Media Department of the police",
        "emails": [],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-adek-aa",
    "name": "ADEk- AA",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "Mr. Ahmad Al Shamsi",
        "position": "مدير مكتب العين",
        "emails": [
          "Ahmed.alshamisi@adek.gov.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-al-ain-court",
    "name": "Al Ain Court",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "Mohammed Rashid Al Neyadi",
        "position": "المدير الاداري لمحاكم مدينة العين",
        "emails": [],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-al-ain-department-of-economic-development",
    "name": "Al Ain Department of Economic Development",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "Khalid Hamar Ain",
        "position": "مدير سلطة ابوظبي للتسجيل- منطقة العين",
        "emails": [
          "Dedcpost@ded.abudhabi.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-al-ain-farms",
    "name": "Al Ain Farms",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "حسان صافي",
        "position": "الرئيس التنفيذي لمزارع العين",
        "emails": [
          "CEO_OFFICE@alainfarms.com"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-al-ain-municipality",
    "name": "Al Ain Municipality",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "Mr. Mubarak Al Shamesi",
        "position": "Knowledge and Innovation Management at Al Ain City Municipality",
        "emails": [],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-blood-bank",
    "name": "Blood Bank",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "Mr. Hamad Saif Saeed Al Nuaimi",
        "position": "Blood Bank Manager",
        "emails": [],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-civil-defence",
    "name": "Civil Defence",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "سعادة العقيد/ مظفر محمد العامري",
        "position": "مدير إدارة الإنقاذ والأطفاء، هيئة أبوظبي للدفاع المدني، منطقة العين",
        "emails": [],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-cybersecurity-council",
    "name": "Cybersecurity Council",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "H.E. Dr. Mohamed Al Kuwaiti",
        "position": "Head of Cyber Security for the UAE Government",
        "emails": [],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-department-of-culture-tourism",
    "name": "Department of Culture & Tourism",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "Hend Al Dhahri",
        "position": "Outreach Unit Head - Education and Outreach",
        "emails": [
          "hend.aldhaheri@dctabudhabi.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-emirates-cancer-society",
    "name": "Emirates Cancer Society",
    "category": "individual",
    "mou": false,
    "contacts": [
      {
        "name": "Emirates Cancer Society",
        "emails": [],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-emirates-cancer-societys",
    "name": "Emirates Cancer Society's",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "HE Sheikh Dr. Salem Balrakkad Alameri",
        "position": "Chairman of the Board",
        "emails": [],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-emirates-red-crescent",
    "name": "Emirates Red Crescent",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "Dr. Ahmad Obaid Al Dhahri",
        "position": "Director of the ERC Al Ain Center,",
        "emails": [
          "a.aldhaheri@rcuae.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-emirates-steel-arkan-group",
    "name": "Emirates Steel-Arkan Group",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "محمد العفاري",
        "position": "VP marketing at Emirates Steel Industries",
        "emails": [
          "Mohammed.afari@emiratessteel.com"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-etisalat",
    "name": "Etisalat",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "عبدالله يوسف الحمادي",
        "position": "مدير الفرع الرئيسي بالعين",
        "emails": [],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-mediclinic",
    "name": "MEDICLINIC",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "Dr. Tariq Shadid",
        "position": "Medical Director",
        "emails": [
          "Tariq.Shadid@mediclinic.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-seha",
    "name": "SEHA",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "Dr. Sultan Mohamed Alkaram",
        "position": "Chief Executive Officer | Al Ain Region",
        "emails": [],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-strata",
    "name": "Strata",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "Mr. Ismail Ali Abdulla",
        "position": "Managing Director",
        "emails": [
          "iaabdulla@strata.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-tadweer",
    "name": "TADWEER",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "Mr. Ali Al Dhaheri",
        "position": "CEO and Managing Director",
        "emails": [
          "gmo@tadweer.gov.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-taqa",
    "name": "TAQA",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "Mr. Qais Al Suwaidi",
        "position": "Vice President of Sustainability",
        "emails": [
          "Qais.Alsuwaidi@taqa.com"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-the-national-media-council-nmc-al-ain",
    "name": "The National Media Council (NMC) - Al Ain",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "The National Media Council (NMC) - Al Ain",
        "emails": [],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-zayed-higher-organization-for-humanitarian-care-special-needs",
    "name": "Zayed Higher Organization for Humanitarian Care & Special Needs",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "السيدة غبيشة العامري",
        "position": "مديرة مركز مؤسسة زايد العليا لأصحاب الهمم بالعين",
        "emails": [],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-org-6",
    "name": "السفير الأردني",
    "category": "individual",
    "mou": false,
    "contacts": [
      {
        "name": "السفير الأردني",
        "emails": [
          "Abudhabi@fm.gov.jo"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-ambassador-tirmizi",
    "name": "السفير الباكستاني Ambassador Tirmizi",
    "category": "individual",
    "mou": false,
    "contacts": [
      {
        "name": "السفير الباكستاني Ambassador Tirmizi",
        "emails": [
          "mkazmipk1910@gmail.com",
          "ambassador@pakistanembassyuae.org"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-org",
    "name": "الشيخ محمد بن حم العامري",
    "category": "individual",
    "mou": false,
    "contacts": [
      {
        "name": "الشيخ محمد بن حم العامري",
        "emails": [],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-org-8",
    "name": "جهاز الامارات للمحاسبة",
    "category": "individual",
    "subtype": "Advisory Board",
    "mou": false,
    "contacts": [
      {
        "name": "هيفاء الشمري",
        "position": "مدير إدارة الموارد البشرية في جهاز الامارات للمحاسبة",
        "emails": [
          "info@uaeaa.gov.ae"
        ],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-org-2",
    "name": "حشيمة العفاري",
    "category": "individual",
    "mou": false,
    "contacts": [
      {
        "name": "حشيمة العفاري",
        "position": "عضو مجلس وطني",
        "emails": [],
        "phones": [
          "052 774 3331"
        ]
      }
    ]
  },
  {
    "id": "ind-org-3",
    "name": "حميد الشمري",
    "category": "individual",
    "mou": false,
    "contacts": [
      {
        "name": "حميد الشمري",
        "position": "نائب مدير مبادلة",
        "emails": [],
        "phones": [
          "00521999991"
        ]
      }
    ]
  },
  {
    "id": "ind-org-7",
    "name": "دكتور عبدالله الشمري",
    "category": "individual",
    "mou": false,
    "contacts": [
      {
        "name": "دكتور عبدالله الشمري",
        "emails": [],
        "phones": [
          "055 333 3742"
        ]
      }
    ]
  },
  {
    "id": "ind-org-5",
    "name": "محمد بن عمير الشامسي",
    "category": "individual",
    "mou": false,
    "contacts": [
      {
        "name": "محمد بن عمير الشامسي",
        "emails": [],
        "phones": []
      }
    ]
  },
  {
    "id": "ind-org-4",
    "name": "منصور المنصوري",
    "category": "individual",
    "mou": false,
    "contacts": [
      {
        "name": "منصور المنصوري",
        "position": "رئيس فريق كاميرا الإمارات للتصوير",
        "emails": [
          "ecp.emirates@gmail.com"
        ],
        "phones": []
      }
    ]
  }
];
// </auto>
