// Generated by scripts/import-schools.mjs — Al Ain schools (English), for the
// registration school picker + the schools-directory fallback. Do not hand-edit.
export type School = { id: string; name: string; category?: string };

export const SCHOOLS: School[] = [
  {
    "id": "school-aaliya",
    "name": "AALIYA",
    "category": "Public"
  },
  {
    "id": "school-abdullah-bin-zubair-private-school",
    "name": "Abdullah Bin Zubair Private school",
    "category": "Private"
  },
  {
    "id": "school-abu-dhabi-island-school",
    "name": "Abu Dhabi Island School",
    "category": "Private"
  },
  {
    "id": "school-ahmed-bin-zayed",
    "name": "AHMED BIN ZAYED",
    "category": "Public"
  },
  {
    "id": "school-ain-al-khaleej-private-school",
    "name": "Ain Al Khaleej Private School",
    "category": "Private"
  },
  {
    "id": "school-ain-al-khaleej-school",
    "name": "AIN AL KHALEEJ SCHOOL",
    "category": "Private"
  },
  {
    "id": "school-al-adhwaa-private-school",
    "name": "Al Adhwaa Private School",
    "category": "Private"
  },
  {
    "id": "school-al-adl",
    "name": "AL ADL",
    "category": "Public"
  },
  {
    "id": "school-al-ain",
    "name": "AL AIN",
    "category": "Public"
  },
  {
    "id": "school-al-ain-american-private-school",
    "name": "AL AIN AMERICAN PRIVATE SCHOOL",
    "category": "Private"
  },
  {
    "id": "school-al-ain-american-school",
    "name": "Al Ain American School",
    "category": "Private"
  },
  {
    "id": "school-al-ain-english-speaking-school",
    "name": "Al Ain English Speaking School",
    "category": "Private"
  },
  {
    "id": "school-al-ain-juniors-private-school",
    "name": "Al Ain Juniors Private School",
    "category": "Private"
  },
  {
    "id": "school-al-amirah-kg",
    "name": "Al Amirah KG",
    "category": "Public"
  },
  {
    "id": "school-al-andalus-private-academy",
    "name": "AL ANDALUS PRIVATE ACADEMY",
    "category": "Private"
  },
  {
    "id": "school-al-ataa",
    "name": "AL ATAA",
    "category": "Public"
  },
  {
    "id": "school-al-awael-kg",
    "name": "AL AWAEL KG",
    "category": "Public"
  },
  {
    "id": "school-al-awael-private-school",
    "name": "AL AWAEL PRIVATE SCHOOL",
    "category": "Private"
  },
  {
    "id": "school-al-badiyah",
    "name": "AL BADIYAH",
    "category": "Public"
  },
  {
    "id": "school-al-bedaa",
    "name": "AL BEDAA",
    "category": "Public"
  },
  {
    "id": "school-al-borooj",
    "name": "AL BOROOJ",
    "category": "Public"
  },
  {
    "id": "school-al-dahmaa",
    "name": "AL DAHMAA",
    "category": "Public"
  },
  {
    "id": "school-al-danat",
    "name": "AL DANAT",
    "category": "Public"
  },
  {
    "id": "school-al-dar-academy",
    "name": "Al Dar Academy",
    "category": "Private"
  },
  {
    "id": "school-al-dar-private-school",
    "name": "AL DAR PRIVATE SCHOOL",
    "category": "Private"
  },
  {
    "id": "school-al-dhafra-private-schools-al-ain",
    "name": "Al Dhafra Private Schools-Al Ain",
    "category": "Private"
  },
  {
    "id": "school-al-dhahera",
    "name": "AL DHAHERA",
    "category": "Public"
  },
  {
    "id": "school-al-diwan-kg",
    "name": "AL DIWAN KG",
    "category": "Public"
  },
  {
    "id": "school-al-falah-school-al-khabisi",
    "name": "Al Falah School - Al Khabisi",
    "category": "Private"
  },
  {
    "id": "school-al-falah-school-jimi",
    "name": "Al Falah School - Jimi",
    "category": "Private"
  },
  {
    "id": "school-al-fouaah",
    "name": "AL FOUAAH",
    "category": "Public"
  },
  {
    "id": "school-al-ghaf-charter-school",
    "name": "Al Ghaf Charter School"
  },
  {
    "id": "school-al-ghaith",
    "name": "AL GHAITH",
    "category": "Public"
  },
  {
    "id": "school-al-hamdaniya-grand-private-school-llc",
    "name": "AL HAMDANIYA GRAND PRIVATE SCHOOL L.L.C.",
    "category": "Private"
  },
  {
    "id": "school-al-hayar",
    "name": "AL HAYAR",
    "category": "Public"
  },
  {
    "id": "school-al-hemmah",
    "name": "AL HEMMAH",
    "category": "Public"
  },
  {
    "id": "school-al-hosson",
    "name": "AL HOSSON",
    "category": "Public"
  },
  {
    "id": "school-al-israa-private-school",
    "name": "AL ISRAA PRIVATE SCHOOL",
    "category": "Private"
  },
  {
    "id": "school-al-ittihad-national-private-school-al-ain",
    "name": "Al Ittihad National Private School - Al Ain",
    "category": "Private"
  },
  {
    "id": "school-al-jahili",
    "name": "AL JAHILI",
    "category": "Public"
  },
  {
    "id": "school-al-jimi-kg",
    "name": "AL JIMI KG",
    "category": "Public"
  },
  {
    "id": "school-al-jood",
    "name": "AL JOOD",
    "category": "Public"
  },
  {
    "id": "school-al-joori",
    "name": "Al Joori",
    "category": "Public"
  },
  {
    "id": "school-al-khair",
    "name": "AL KHAIR",
    "category": "Public"
  },
  {
    "id": "school-al-maali",
    "name": "AL MAALI",
    "category": "Public"
  },
  {
    "id": "school-al-maqam",
    "name": "AL MAQAM",
    "category": "Public"
  },
  {
    "id": "school-al-maseera",
    "name": "AL MASEERA",
    "category": "Public"
  },
  {
    "id": "school-al-naeem",
    "name": "AL NAEEM",
    "category": "Public"
  },
  {
    "id": "school-al-nahyaniyyah",
    "name": "AL NAHYANIYYAH",
    "category": "Public"
  },
  {
    "id": "school-al-nebras",
    "name": "AL NEBRAS",
    "category": "Public"
  },
  {
    "id": "school-al-quaa",
    "name": "AL QUAA",
    "category": "Public"
  },
  {
    "id": "school-al-raqiah",
    "name": "AL RAQIAH",
    "category": "Public"
  },
  {
    "id": "school-al-resalah",
    "name": "AL RESALAH",
    "category": "Public"
  },
  {
    "id": "school-al-saad-indian-school-al-ain",
    "name": "Al Saad Indian School Al Ain",
    "category": "Private"
  },
  {
    "id": "school-al-sadarah",
    "name": "AL SADARAH",
    "category": "Public"
  },
  {
    "id": "school-al-salamat",
    "name": "AL SALAMAT",
    "category": "Public"
  },
  {
    "id": "school-al-sanawbar-private-school",
    "name": "Al Sanawbar Private School",
    "category": "Private"
  },
  {
    "id": "school-al-sariyah",
    "name": "AL SARIYAH",
    "category": "Public"
  },
  {
    "id": "school-al-seddique-private-school",
    "name": "AL SEDDIQUE PRIVATE SCHOOL",
    "category": "Private"
  },
  {
    "id": "school-al-shaheen",
    "name": "AL SHAHEEN",
    "category": "Public"
  },
  {
    "id": "school-al-shiyam",
    "name": "AL SHIYAM",
    "category": "Public"
  },
  {
    "id": "school-al-showaib",
    "name": "AL SHOWAIB",
    "category": "Public"
  },
  {
    "id": "school-al-somou",
    "name": "AL SOMOU",
    "category": "Public"
  },
  {
    "id": "school-al-tafawwoq-al-ain",
    "name": "AL TAFAWWOQ (AL AIN)",
    "category": "Public"
  },
  {
    "id": "school-al-tafawwuq-al-ilmi-private-school",
    "name": "AL TAFAWWUQ AL ILMI PRIVATE SCHOOL",
    "category": "Private"
  },
  {
    "id": "school-al-taleaa",
    "name": "AL TALEAA",
    "category": "Public"
  },
  {
    "id": "school-al-tamayyoz",
    "name": "AL TAMAYYOZ",
    "category": "Public"
  },
  {
    "id": "school-al-tawyah-kg",
    "name": "AL TAWYAH KG",
    "category": "Public"
  },
  {
    "id": "school-al-tomooh",
    "name": "AL TOMOOH",
    "category": "Public"
  },
  {
    "id": "school-al-wajan",
    "name": "AL WAJAN",
    "category": "Public"
  },
  {
    "id": "school-al-yahar-kg",
    "name": "AL YAHAR KG",
    "category": "Public"
  },
  {
    "id": "school-al-yahar-private-school-and-kindergarten",
    "name": "AL YAHAR PRIVATE SCHOOL and KINDERGARTEN",
    "category": "Private"
  },
  {
    "id": "school-al-yaher-private-school",
    "name": "Al Yaher Private School",
    "category": "Private"
  },
  {
    "id": "school-al-zayediyyah",
    "name": "AL ZAYEDIYYAH",
    "category": "Public"
  },
  {
    "id": "school-al-zayediyyah-for-girls",
    "name": "AL ZAYEDIYYAH FOR GIRLS",
    "category": "Public"
  },
  {
    "id": "school-al-dhafra-academy",
    "name": "Al- Dhafra Academy",
    "category": "Private"
  },
  {
    "id": "school-ali-bin-abi-taleb",
    "name": "ALI BIN ABI TALEB",
    "category": "Public"
  },
  {
    "id": "school-alkhalil-international-private-schools",
    "name": "ALKHALIL INTERNATIONAL PRIVATE SCHOOLS",
    "category": "Private"
  },
  {
    "id": "school-american-national-school",
    "name": "American National School",
    "category": "Private"
  },
  {
    "id": "school-atfal-al-hilal-kg",
    "name": "ATFAL AL HILAL KG",
    "category": "Public"
  },
  {
    "id": "school-baraaim-al-ain-private-school",
    "name": "Baraaim Al Ain Private School",
    "category": "Private"
  },
  {
    "id": "school-baraem-al-ain-private-schools",
    "name": "BARAEM AL AIN PRIVATE SCHOOLS",
    "category": "Private"
  },
  {
    "id": "school-bin-ham",
    "name": "BIN HAM",
    "category": "Public"
  },
  {
    "id": "school-bin-khaldoon-islamic-private-school",
    "name": "BIN KHALDOON ISLAMIC PRIVATE SCHOOL",
    "category": "Private"
  },
  {
    "id": "school-brighton-college-al-ain",
    "name": "Brighton College Al Ain",
    "category": "Private"
  },
  {
    "id": "school-bu-koreyya",
    "name": "BU KOREYYA",
    "category": "Public"
  },
  {
    "id": "school-dar-al-uloom-private-school-falaj-hazza-branch",
    "name": "DAR AL ULOOM PRIVATE SCHOOL - FALAJ HAZZA BRANCH",
    "category": "Private"
  },
  {
    "id": "school-darul-huda-islamic-school",
    "name": "Darul Huda Islamic School",
    "category": "Private"
  },
  {
    "id": "school-emirates-falcon-international-private-school",
    "name": "Emirates Falcon International Private School",
    "category": "Private"
  },
  {
    "id": "school-emirates-national-school",
    "name": "Emirates National School",
    "category": "Private"
  },
  {
    "id": "school-emirates-national-schools",
    "name": "Emirates National Schools",
    "category": "Private"
  },
  {
    "id": "school-emirates-private-school",
    "name": "Emirates Private School",
    "category": "Private"
  },
  {
    "id": "school-first-lebanon-school-and-kindergarten-llc",
    "name": "FIRST LEBANON SCHOOL AND KINDERGARTEN -LLC",
    "category": "Private"
  },
  {
    "id": "school-future-academy",
    "name": "Future Academy",
    "category": "Private"
  },
  {
    "id": "school-future-international-school",
    "name": "Future International School",
    "category": "Private"
  },
  {
    "id": "school-global-english-school",
    "name": "Global English School",
    "category": "Private"
  },
  {
    "id": "school-grace-valley-indian-school",
    "name": "Grace Valley Indian School",
    "category": "Private"
  },
  {
    "id": "school-hessa-bint-mohammad",
    "name": "HESSA BINT MOHAMMAD",
    "category": "Public"
  },
  {
    "id": "school-hili",
    "name": "HILI",
    "category": "Public"
  },
  {
    "id": "school-ibn-khaldoun-islamic-school",
    "name": "Ibn Khaldoun Islamic School",
    "category": "Private"
  },
  {
    "id": "school-indian-school",
    "name": "Indian School",
    "category": "Private"
  },
  {
    "id": "school-indian-school-alain",
    "name": "Indian school Alain"
  },
  {
    "id": "school-international-private-school",
    "name": "International Private School",
    "category": "Private"
  },
  {
    "id": "school-international-school-of-choueifat-al-ain",
    "name": "International School of Choueifat - Al Ain",
    "category": "Private"
  },
  {
    "id": "school-khaled-bin-al-waleed",
    "name": "KHALED BIN AL WALEED",
    "category": "Public"
  },
  {
    "id": "school-khalifah-bin-zayed-al-ain",
    "name": "KHALIFAH BIN ZAYED (AL AIN)",
    "category": "Public"
  },
  {
    "id": "school-lebanon-first-school-and-kindergarten-llc",
    "name": "LEBANON FIRST SCHOOL AND KINDERGARTEN -LLC",
    "category": "Private"
  },
  {
    "id": "school-lebanon-the-first-private-school",
    "name": "Lebanon the First Private School",
    "category": "Private"
  },
  {
    "id": "school-liwa-international-school-2nd-term",
    "name": "Liwa International School 2nd TERM",
    "category": "Private"
  },
  {
    "id": "school-liwa-international-school-falaj-haza",
    "name": "LIWA international school falaj Haza"
  },
  {
    "id": "school-liwa-international-school-for-girls",
    "name": "Liwa International School for Girls",
    "category": "Private"
  },
  {
    "id": "school-liwa-international-school-falaj-hazza",
    "name": "Liwa International School-Falaj Hazza",
    "category": "Private"
  },
  {
    "id": "school-liwa-school-for-girls",
    "name": "Liwa School for girls",
    "category": "Private"
  },
  {
    "id": "school-madar-international-school",
    "name": "Madar International School",
    "category": "Private"
  },
  {
    "id": "school-manor-hall-private-school",
    "name": "Manor Hall Private School",
    "category": "Private"
  },
  {
    "id": "school-maryam-bint-sultan",
    "name": "MARYAM BINT SULTAN",
    "category": "Public"
  },
  {
    "id": "school-mbazzarah-al-khadra",
    "name": "Mbazzarah Al Khadra",
    "category": "Public"
  },
  {
    "id": "school-mohammed-bin-khaled",
    "name": "MOHAMMED BIN KHALED",
    "category": "Public"
  },
  {
    "id": "school-muraijib",
    "name": "MURAIJIB",
    "category": "Public"
  },
  {
    "id": "school-nahel",
    "name": "NAHEL",
    "category": "Public"
  },
  {
    "id": "school-nahyan-al-awal-kg",
    "name": "Nahyan Al Awal KG",
    "category": "Public"
  },
  {
    "id": "school-neima",
    "name": "NEIMA",
    "category": "Public"
  },
  {
    "id": "school-neima-c3-boys",
    "name": "Neima C3 Boys",
    "category": "Public"
  },
  {
    "id": "school-new-indian-model-school",
    "name": "New Indian Model School",
    "category": "Private"
  },
  {
    "id": "school-new-mezyad",
    "name": "NEW MEZYAD",
    "category": "Public"
  },
  {
    "id": "school-newcentury-education",
    "name": "Newcentury Education"
  },
  {
    "id": "school-oasis-international-school",
    "name": "Oasis International School",
    "category": "Private"
  },
  {
    "id": "school-our-own-english-high-school",
    "name": "Our Own English High School",
    "category": "Private"
  },
  {
    "id": "school-pakistan-islamic-private-school",
    "name": "Pakistan Islamic Private School",
    "category": "Private"
  },
  {
    "id": "school-palestine-private-academy-llc",
    "name": "PALESTINE PRIVATE ACADEMY L.L.C.",
    "category": "Private"
  },
  {
    "id": "school-ramah",
    "name": "RAMAH",
    "category": "Public"
  },
  {
    "id": "school-reefaa",
    "name": "REEFAA",
    "category": "Public"
  },
  {
    "id": "school-scientific-distinction-private-school",
    "name": "Scientific Distinction Private School",
    "category": "Private"
  },
  {
    "id": "school-shakhbout-bin-sultan",
    "name": "SHAKHBOUT BIN SULTAN",
    "category": "Public"
  },
  {
    "id": "school-shamma-bint-mohammad",
    "name": "SHAMMA BINT MOHAMMAD",
    "category": "Public"
  },
  {
    "id": "school-sheikha-bint-suroor",
    "name": "SHEIKHA BINT SUROOR",
    "category": "Public"
  },
  {
    "id": "school-sultan-bin-zayed",
    "name": "SULTAN BIN ZAYED",
    "category": "Public"
  },
  {
    "id": "school-tahnoon-bin-mohammad",
    "name": "TAHNOON BIN MOHAMMAD",
    "category": "Public"
  },
  {
    "id": "school-tawam-private-model-school",
    "name": "TAWAM PRIVATE MODEL SCHOOL",
    "category": "Private"
  },
  {
    "id": "school-the-gulf-international-private-academy",
    "name": "The Gulf International Private Academy",
    "category": "Private"
  },
  {
    "id": "school-tifel-al-emarat-kg",
    "name": "TIFEL AL EMARAT KG",
    "category": "Public"
  },
  {
    "id": "school-tolerance-schools-al-mutarid",
    "name": "Tolerance Schools - Al Mutarid",
    "category": "Public"
  },
  {
    "id": "school-um-al-emarat-al-ain",
    "name": "UM AL EMARAT (AL AIN)",
    "category": "Public"
  },
  {
    "id": "school-um-al-fadhel-bint-al-hareth",
    "name": "UM AL FADHEL BINT AL HARETH",
    "category": "Public"
  },
  {
    "id": "school-um-ghafa",
    "name": "UM GHAFA",
    "category": "Public"
  },
  {
    "id": "school-um-ghafa-kg",
    "name": "UM GHAFA KG",
    "category": "Public"
  },
  {
    "id": "school-um-kolthoom",
    "name": "UM KOLTHOOM",
    "category": "Public"
  },
  {
    "id": "school-united-school-of-al-yahar",
    "name": "United School of Al Yahar",
    "category": "Private"
  },
  {
    "id": "school-universal-private-school-llc",
    "name": "UNIVERSAL PRIVATE SCHOOL L.L.C.",
    "category": "Private"
  },
  {
    "id": "school-zakher-private-school",
    "name": "ZAKHER PRIVATE SCHOOL",
    "category": "Private"
  },
  {
    "id": "school-zakher-private-school-al-ain",
    "name": "Zakher Private School, Al Ain"
  },
  {
    "id": "school-zayed-al-awal",
    "name": "ZAYED AL AWAL",
    "category": "Public"
  }
];
