// ETL: build the English schools directory from "Gala Dinner List (1).xlsx"
// (sheets "Schools" + "Schools with MOU"). Writes:
//   - src/lib/schools-data.ts        (typed seed; fallback + types)
//   - supabase/seeds/schools.sql     (INSERT block for the schools table)
// Run: node scripts/import-schools.mjs
import * as XLSX from "xlsx";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const wb = XLSX.read(readFileSync(join(ROOT, "Gala Dinner List (1).xlsx")), { type: "buffer" });

const clean = (v) => String(v ?? "").replace(/\s+/g, " ").trim();
const hasLatin = (s) => /[A-Za-z]/.test(s);
const slug = (s, used) => {
  let base =
    "school-" +
    s.toLowerCase().normalize("NFKD").replace(/[^a-z0-9\s-]/g, "").trim().replace(/\s+/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "");
  let out = base, n = 2;
  while (used.has(out)) out = `${base}-${n++}`;
  used.add(out);
  return out;
};

function rows(sheet) {
  const ws = wb.Sheets[sheet];
  if (!ws) return [];
  return XLSX.utils.sheet_to_json(ws, { header: 1, defval: "", blankrows: false, raw: false });
}
function headerIdx(hdr) {
  const m = {};
  hdr.forEach((h, i) => { const k = clean(h).toLowerCase(); if (k && !(k in m)) m[k] = i; });
  return m;
}

const seen = new Map();
function collect(sheet) {
  const r = rows(sheet);
  if (!r.length) return;
  // The EN-name header is corrupted in the source ("Sch+A:Mool_Name_EN"), so
  // match by pattern rather than exact key.
  const iEn = r[0].findIndex((h) => /(?:school|mool)_name_en/i.test(clean(h)));
  const iCat = r[0].findIndex((h) => /category_en/i.test(clean(h)));
  for (const row of r.slice(1)) {
    const name = clean(row[iEn]);
    if (!name || !hasLatin(name)) continue; // English names only
    const key = name.toLowerCase();
    if (seen.has(key)) continue;
    const cat = clean(row[iCat]);
    seen.set(key, { name, category: /private/i.test(cat) ? "Private" : /public/i.test(cat) ? "Public" : "" });
  }
}
collect("Schools with MOU");
collect("Schools");

const used = new Set();
const schools = [...seen.values()]
  .sort((a, b) => a.name.localeCompare(b.name))
  .map((s) => ({ id: slug(s.name, used), name: s.name, category: s.category || undefined }));

// TS seed
const ts = `// Generated by scripts/import-schools.mjs — Al Ain schools (English), for the
// registration school picker + the schools-directory fallback. Do not hand-edit.
export type School = { id: string; name: string; category?: string };

export const SCHOOLS: School[] = ${JSON.stringify(schools, null, 2)};
`;
writeFileSync(join(ROOT, "src/lib/schools-data.ts"), ts);

// SQL seed
const esc = (s) => s.replace(/'/g, "''");
const values = schools
  .map((s) => `  ('${s.id}', '${esc(s.name)}', ${s.category ? `'${s.category}'` : "null"})`)
  .join(",\n");
const sql = `-- Generated by scripts/import-schools.mjs — run as part of 0003.
insert into schools (id, name, category) values
${values}
on conflict (id) do nothing;
`;
mkdirSync(join(ROOT, "supabase/seeds"), { recursive: true });
writeFileSync(join(ROOT, "supabase/seeds/schools.sql"), sql);

console.log(`schools: ${schools.length} (Private: ${schools.filter((s) => s.category === "Private").length}, Public: ${schools.filter((s) => s.category === "Public").length})`);
console.log("wrote src/lib/schools-data.ts and supabase/seeds/schools.sql");
